[package]
name = "roastr-server"
version = "0.2.1"
authors = ["m1sterc001guy"]
edition = "2021"
description = "A federated nostr client."
license = "MIT"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[lib]
name = "roastr_server"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.73"
anyhow = { workspace = true }
fedimint-core = { workspace = true }
fedimint-server = { workspace = true }
futures = "0.3.28"
itertools = "0.12.1"
erased-serde = "0.4.4"
nostr-sdk = { workspace = true }
rand = { workspace = true }
roastr-common = { path = "../roastr-common" }
schnorr_fun = { workspace = true }
sha2 = { workspace = true }
serde = { version = "1.0.149", features = [ "derive" ] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
strum = "0.26.2"
strum_macros = "0.26.2"
tracing = { workspace = true }
