[package]
name = "roastr-tests"
version = "0.0.1"
authors = ["m1sterc001guy"]
edition = "2021"
description = "A federated nostr client."
license = "MIT"
publish = false

[[test]]
name = "roastr_tests"
path = "tests/tests.rs"

[dependencies]
fedimint-dummy-client = { git = "https://github.com/m1sterc001guy/fedimint", rev = "2541b9705aefde724d55683aa46fb6997d312d7e" }
fedimint-dummy-common = { git = "https://github.com/m1sterc001guy/fedimint", rev = "2541b9705aefde724d55683aa46fb6997d312d7e" }
fedimint-dummy-server = { git = "https://github.com/m1sterc001guy/fedimint", rev = "2541b9705aefde724d55683aa46fb6997d312d7e" }
fedimint-wallet-client = { git = "https://github.com/m1sterc001guy/fedimint", rev = "2541b9705aefde724d55683aa46fb6997d312d7e" }
fedimint-wallet-common = { git = "https://github.com/m1sterc001guy/fedimint", rev = "2541b9705aefde724d55683aa46fb6997d312d7e" }
fedimint-wallet-server = { git = "https://github.com/m1sterc001guy/fedimint", rev = "2541b9705aefde724d55683aa46fb6997d312d7e" }

anyhow = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
roastr-client = { path = "../roastr-client" }
roastr-common = { path = "../roastr-common" }
roastr-server = { path = "../roastr-server" }
fedimint-logging = { workspace = true }
fedimint-server = { workspace = true }
fedimint-testing = { workspace = true }
nostr-sdk = { workspace = true }
rand = { workspace = true }
tokio = { version = "1.26.0", features = ["sync"] }
tracing = { workspace = true }
schnorr_fun = { workspace = true }
sha2 = { workspace = true }